version: '3.8'

services:
  # FRP服务端 (部署在有公网IP的服务器上)
  frps:
    build:
      context: .
      dockerfile: docker/frp/frps/Dockerfile
    image: openvpn-frp/frps:latest
    container_name: frps
    restart: unless-stopped
    ports:
      - "7000:7000"    # FRP控制端口
      - "7500:7500"    # 管理后台端口
      - "1194:1194/udp" # OpenVPN端口映射
      - "7505:7505"    # OpenVPN管理端口映射
      - "8080:8080"    # Web管理端口映射
    volumes:
      - ./config/frps.ini:/opt/frp/conf/frps.ini:ro
      - ./logs/frps:/opt/frp/logs
    environment:
      - TZ=Asia/Shanghai
    networks:
      - frp-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "7000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # FRP客户端 (部署在OpenVPN所在的内网环境)
  frpc:
    build:
      context: .
      dockerfile: docker/frp/frpc/Dockerfile
    image: openvpn-frp/frpc:latest
    container_name: frpc
    restart: unless-stopped
    volumes:
      - ./config/frpc.ini:/opt/frp/conf/frpc.ini:ro
      - ./logs/frpc:/opt/frp/logs
    environment:
      - TZ=Asia/Shanghai
      - OPENVPN_HOST=openvpn
      - OPENVPN_PORT=1194
    networks:
      - frp-network
      - openvpn-network
    depends_on:
      - openvpn
    healthcheck:
      test: ["CMD", "pgrep", "frpc"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # OpenVPN服务 (从现有配置引用)
  openvpn:
    build:
      context: .
      dockerfile: docker/openvpn/Dockerfile
    image: openvpn-frp/openvpn:latest
    container_name: openvpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "1194:1194/udp"
      - "7505:7505"    # 管理接口
    volumes:
      - ./config/server.conf:/etc/openvpn/server.conf:ro
      - ./pki:/etc/openvpn/pki:ro
      - ./logs/openvpn:/var/log/openvpn
    environment:
      - TZ=Asia/Shanghai
    networks:
      - openvpn-network
    healthcheck:
      test: ["CMD", "pgrep", "openvpn"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  frp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
  
  openvpn-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

volumes:
  frps-logs:
    driver: local
  frpc-logs:
    driver: local
  openvpn-logs:
    driver: local